= 00: Conflict
Encounter with a street gang

Lucid City. I have returned after a very long time has passed. Ever since that
time, I've been running without anywhere to go. Hiding from vicious beasts that
glows in pack. Living under the shadows created by my shining hand. Praying that
no dangerous beasts stalking behind me, let alone attacking.

It was about six years since my last visit. It was the very first city that I
have ever seen in my life. And I was there when it fell to the ground, nearly
flat out, two weeks later. I remembered so well how the swarm attacked the
building I was in that time. How they took my dearest family away. I couldn't
take it when I found my parents lying on the ground, lifeless. And the fact that
my brother disappeared always running in my weak little mind.

Things have changed now. The government claimed that they have found a way to
light up a place without attracting the threat that they call as "Neon Bugs".
They strongly believe that it will prevent them from coming any further.
Or so they said.

The city itself has changed _a lot_. Buildings scrape higher than they
previously were. The night that once haunted with the silence and the fear of
light that may attract the bugs, now becomes illuminated, vibrant, and noisy.
I can barely find any remains of the destruction of the past. Even the flattened
stadium returned to its old glory like nothing has happened before.

I am currently passing through the Austern Bridge. It was built to connect two
districts: Lucid and Greptome. 
